doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Room\Entity\Room:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Room/Entity'
                prefix: 'App\Domain\Room\Entity'
                alias: App\Domain\Room
            App\Domain\Player\Entity\Player:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Player/Entity'
                prefix: 'App\Domain\Player\Entity'
                alias: App\Domain\Player
            App\Domain\Mission\Entity\Mission:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Mission/Entity'
                prefix: 'App\Domain\Mission\Entity'
                alias: App\Domain\Mission

when@test:
    doctrine:
        dbal:
            url: '%env(resolve:DATABASE_URL_TEST)%'
            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
