mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'

when@test:
    mercure:
        hubs:
            default:
                url: 'mercure'
                public_url: 'public-mercure'
                jwt:
                    secret: 'secret'
                    publish: '*'
