security:
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Domain\Player\Entity\Player
                property: id
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern: ^/player
            methods: [POST]
            stateless: true
            lazy: true
            provider: app_user_provider
        refresh_token:
            pattern: ^/refresh-token
            methods: [POST]
            stateless: true
            lazy: true
            provider: app_user_provider
        main:
            stateless: true
            lazy: true
            provider: app_user_provider
            jwt: ~

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_MASTER: ROLE_ADMIN


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/health, roles: PUBLIC_ACCESS }
         - { path: ^/_mcp, roles: PUBLIC_ACCESS }
         - { path: ^/player, roles: PUBLIC_ACCESS, method: [POST] }
         - { path: ^/refresh-token, roles: PUBLIC_ACCESS }
         - { path: ^/player, roles: ROLE_USER }
         - { path: ^/room, roles: ROLE_USER }
         - { path: ^/mission, roles: ROLE_USER }
