framework:
    workflows:
        room_lifecycle:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Domain\Room\Entity\Room
            initial_marking: PENDING
            places:
                - PENDING
                - IN_GAME
                - ENDED
            transitions:
                start_game:
                    guard: "is_granted('edit_room', subject)"
                    from: PENDING
                    to: IN_GAME
                end_game:
                    from: IN_GAME
                    to: ENDED
