# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: ${APP_ENV:-prod}
      SERVER_NAME: ${SERVER_NAME:-api.killerparty.app}
      APP_SECRET: ${APP_SECRET}
      SENTRY_DSN: ${SENTRY_DSN:-}
      EXPO_DSN: ${EXPO_DSN:-}
      DATABASE_URL: ${DATABASE_URL}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://mercure/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-api.killerparty.app}/.well-known/mercure}

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins "https://${SERVER_NAME:-api.killerparty.app}"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
