controllers:
    resource: ../src/Api/Controller/
    type: attribute

gesdinet_jwt_refresh_token:
    path: /refresh-token
    controller: gesdinet.jwtrefreshtoken::refresh

_mcp:
    resource: .
    type: mcp
